# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='age',
        ),
        migrations.RemoveField(
            model_name='students',
            name='gender',
        ),
    ]
